Table dg_postmeta {
  meta_id BigInt [pk, increment]
  post_id BigInt [not null, default: 0]
  meta_key String
  meta_value String
}

Table dg_posts {
  ID BigInt [pk, increment]
  post_author BigInt [not null, default: 0]
  post_date DateTime [not null]
  post_date_gmt DateTime [not null]
  post_content String [not null]
  post_title String [not null]
  post_excerpt String [not null]
  post_status String [not null, default: 'publish']
  comment_status String [not null, default: 'open']
  ping_status String [not null, default: 'open']
  post_password String [not null, default: '']
  post_name String [not null, default: '']
  to_ping String [not null]
  pinged String [not null]
  post_modified DateTime [not null]
  post_modified_gmt DateTime [not null]
  post_content_filtered String [not null]
  post_parent BigInt [not null, default: 0]
  guid String [not null, default: '']
  menu_order Int [not null, default: 0]
  post_type String [not null, default: 'post']
  post_mime_type String [not null, default: '']
  comment_count BigInt [not null, default: 0]
}

Table dg_stm_lms_user_courses {
  user_course_id Int [pk, increment]
  user_id BigInt [not null]
  course_id Int [not null]
  current_lesson_id Int
  progress_percent Int [not null]
  status String [not null, default: '']
  lng_code String [not null, default: 'en_US']
  subscription_id Int
  enterprise_id Int [default: 0]
  bundle_id Int [default: 0]
  start_time Int [not null]
  end_time Int [default: 0]
  for_points String [default: '']
}

Table dg_stm_lms_user_lessons {
  user_lesson_id Int [pk, increment]
  user_id BigInt [not null]
  course_id Int [not null]
  lesson_id Int [not null]
  start_time Int
  end_time Int
}

Table dg_usermeta {
  umeta_id BigInt [pk, increment]
  user_id BigInt [not null, default: 0]
  meta_key String
  meta_value String
}

Table dg_users {
  ID BigInt [pk, increment]
  user_login String [not null, default: '']
  user_pass String [not null, default: '']
  user_nicename String [not null, default: '']
  user_email String [not null, default: '']
  user_url String [not null, default: '']
  user_registered DateTime [not null]
  user_activation_key String [not null, default: '']
  user_status Int [not null, default: 0]
  display_name String [not null, default: '']
}

Table aa_classroom_groups {
  created_at DateTime [default: `now()`, not null]
  updated_at DateTime [not null]
  deleted_at DateTime
  id Int [pk, increment]
  course_id Int [not null]
  group_name String [not null]
  description String [not null]
  cover String [not null]
  avatar String [not null]
  created_by BigInt [not null]
  users_group aa_classroom_group_members [not null]
}

Table aa_classroom_group_members {
  id Int [pk, increment]
  user_id BigInt [not null]
  group_id Int [not null]
  group aa_classroom_groups [not null]
  role GroupRole [not null, default: 'THANHVIEN']
  order Int [not null]
  created_by BigInt [not null]
  created_at DateTime [default: `now()`, not null]
}

Table aa_attendance {
  id Int [pk, increment]
  user_id BigInt [not null]
  course_id Int [not null]
  lesson_id Int [not null]
  status AttendanceStatus [not null]
  created_at DateTime [default: `now()`, not null]
}

Table aa_activity_type {
  id Int [pk, increment]
  name String [not null]
  icon String [not null]
  created_at DateTime [default: `now()`, not null]
  updated_at DateTime [not null]
  activities aa_activity [not null]
}

Table aa_activity {
  created_at DateTime [default: `now()`, not null]
  updated_at DateTime [not null]
  id Int [pk, increment]
  type_id Int [not null]
  type aa_activity_type [not null]
  post_id Int [not null]
  name String [not null]
  min_count Int [not null, default: 1]
  end_date DateTime
  activity_logs aa_activity_logs [not null]
}

Table aa_activity_logs {
  created_at DateTime [default: `now()`, not null]
  updated_at DateTime [not null]
  id BigInt [pk, increment]
  activity_id Int [not null]
  activity aa_activity [not null]
  content String [not null]
  status ActivityStatus [not null]
  created_by BigInt [not null]
}

Table aa_activity_relationships {
  id Int [pk, increment]
  user_id BigInt [not null]
  activity_id Int [not null]
  activity_log_id BigInt [not null]
  created_at DateTime [default: `now()`, not null]
}

Enum ActivityStatus {
  PUBLISH
  DRAFT
}

Enum AttendanceStatus {
  TRONVEN
  VANGMAT
  MUON
}

Enum GroupRole {
  TRUONGTHON
  PHOTHON
  THANHVIEN
}

Ref: aa_classroom_group_members.group_id > aa_classroom_groups.id [delete: Cascade]

Ref: aa_activity.type_id > aa_activity_type.id [delete: Cascade]

Ref: aa_activity_logs.activity_id > aa_activity.id [delete: Cascade]